(defun sweyla886611 ()
  "Theme generated by Sweyla: http://sweyla.com/themes/seed/886611/"
  (interactive)
  (color-theme-install
   '(sweyla886611
     ((background-color . "#000E00")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#2A4A75"))))
     (font-lock-constant-face ((t (:foreground "#87065C"))))
     (font-lock-builtin-face ((t (:foreground "#759100"))))
     (font-lock-function-name-face ((t (:foreground "#1AE11A"))))
     (font-lock-variable-name-face ((t (:foreground "#AD3E38"))))
     (font-lock-keyword-face ((t (:foreground "#486D92"))))
     (font-lock-string-face ((t (:foreground "#3F13BD"))))
     (font-lock-doc-string-face ((t (:foreground "#3F13BD"))))
     (font-lock-type-face ((t (:foreground "#427480"))))
     )))

(provide 'sweyla886611)
